modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="auroraprojects"
version="1.0.0"
displayName="Aurora-project"
credits="nop"
displayURL="https://amazon.fr"
logoFile="logo.png"
authors="Aurora Team"
description='''
Bienvenue sur Aurora
'''

[[dependencies.auroraprojects]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




